<?php

namespace Database\Seeders;

use App\Models\SatuanKerja;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SatuanKerjaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $satker = ["UNIVERSITAS ISLAM NEGERI SUNAN GUNUNG JATI BANDUNG", "UIN RADEN INTAN BANDAR LAMPUNG", "UIN IMAM BONJOL PADANG", "UNIVERSITAS ISLAM NEGERI K.H. ABDURRAHMAN WAHID PEKALONGAN", "UNIVERSITAS ISLAM NEGERI SIBER SYEKH NURJATI CIREBON", "UIN ANTASARI BANJARMASIN", "UNIVERSITAS ISLAM NEGERI PROFESOR KIAI HAJI SAIFUDDIN ZUHRI PURWOKERTO", "IAIN PONOROGO", "UNIVERSITAS ISLAM NEGERI FATMAWATI SUKARNO BENGKULU", "UIN SULTAN MAULANA HASANUDDIN BANTEN", "STAIN BENGKALIS", "UNIVERSITAS ISLAM NEGERI SUNAN AMPEL SURABAYA", "INSTITUT AGAMA ISLAM NEGERI TERNATE", "IAIN PALOPO", "INSTITUT AGAMA ISLAM NEGERI (IAIN) MANADO", "INSTITUT AGAMA ISLAM NEGERI AMBON", "SEKOLAH TINGGI AGAMA ISLAM NEGERI MANDAILING NATAL", "IAIN METRO", "STAIN TEUNGKU DIRUNDENG MEULABOH", "INSTITUT AGAMA ISLAM NEGERI PALANGKARAYA", "IAIN SYAIKH ABDURRAHMAN SIDDIK BANGKA BELITUNG", "IAIN MADURA", "UIN SUMATERA UTARA MEDAN", "UNIVERSITAS ISLAM NEGERI SUNAN KALIJAGA YOGYAKARTA", "INSTITUT AGAMA ISLAM NEGERI (IAIN) ZAWIYAH COT KALA LANGSA", "IAIN KERINCI", "UNIVERSITAS ISLAM NEGERI SAYYID ALI RAHMATULLAH TULUNGAGUNG", "IAIN PAREPARE", "IAIN FATTAHUL MULUK PAPUA", "SEKOLAH TINGGI AGAMA ISLAM NEGERI SULTAN ABDURRAHMAN KEPULAUAN RIAU", "INSTITUT AGAMA ISLAM NEGERI SORONG", "UNIVERSITAS ISLAM NEGERI MAHMUD YUNUS BATUSANGKAR", "IAIN GORONTALO", "IAIN KUDUS", "IAIN CURUP", "UNIVERSITAS ISLAM NEGERI SALATIGA", "UNIVERSITAS ISLAM NEGERI RADEN MAS SAID SURAKARTA", "UIN ALAUDDIN MAKASSAR", "UNIVERSITAS ISLAM NEGERI DATOKARAMA PALU", "Institut Agama Islam Negeri Pontianak", "IAIN KEDIRI", "UNIVERSITAS ISLAM NEGERI SULTAN AJI MUHAMMAD IDRIS SAMARINDA", "Universitas Islam Negeri Ar-Raniry Banda Aceh", "INSTITUT AGAMA ISLAM NEGERI (IAIN) KENDARI", "UIN SULTHAN SYARIF KASIM RIAU", "UIN SULTAN THAHA SAIFUDDIN JAMBI", "UNIVERSITAS ISLAM NEGERI (UIN) MAULANA MALIK IBRAHIM MALANG", "UIN SYARIF HIDAYATULLAH JAKARTA", "UNIVERSITAS ISLAM NEGERI WALISONGO SEMARANG", "UNIVERSITAS ISLAM NEGERI KIAI HAJI ACHMAD SIDDIQ JEMBER", "INSTITUT AGAMA ISLAM NEGERI TAKENGON", "IAIN LHOKSEUMAWE", "UNIVERSITAS ISLAM NEGERI SYEKH ALI HASAN AHMAD ADDARY PADANGSIDIMPUAN", "UNIVERSITAS ISLAM NEGERI SJECH M. DJAMIL DJAMBEK BUKITTINGGI", "UNIVERSITAS ISLAM NEGERI RADEN FATAH PALEMBANG", "IAIN BONE", "UIN MATARAM", "SEKOLAH TINGGI AGAMA ISLAM NEGERI MAJENE"];

        foreach($satker as $s){
            SatuanKerja::create([
                'nama' => $s
            ]);
        }
    }
}
